[package]
name = "ray-tracing-tutorial"
version = "0.1.0"
authors = ["Peter Aarestad <aarestad@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
image = "0.23.14"
threadpool = "1.8.1"
num_cpus = "1.13.0"
pprof = { version = "0.4.3", features = ["flamegraph"] }
