[package]
name = "ray-tracer"
version = "1.7.3"
authors = ["Peter Aarestad <aarestad@gmail.com>"]
edition = "2021"
description = "Trace some rays"

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
image = "0.25.1"
threadpool = "1.8.1"
num_cpus = "1.16.0"
args = "2.2.0"
getopts = "0.2.21"
array-init = "2.1.0"
libwebp-image = "0.3.0"
nalgebra = "0.33.0"
parry3d = "0.16.1"
approx = "0.5.1"
