[package]
name = "ray-tracer"
version = "1.7.3"
authors = ["Peter Aarestad <aarestad@gmail.com>"]
edition = "2021"
description = "Trace some rays"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
rand_distr = "0.4.0"
image = "0.23.14"
threadpool = "1.8.1"
num_cpus = "1.13.0"
args = "2.2.0"
getopts = "0.2.21"
array-init = "2.0.0"
libwebp-image = "0.2.0"
nalgebra = "0.26.1"
parry3d = "0.4.0"
