name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: icepuma/rust-action@1.51.0
        with:
          args: cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test
